[package]
name = "minidump-writer"
version = "0.4.0"
authors = ["Martin Sirringhaus"]
description = "Rust rewrite of Breakpad's minidump_writer"
repository = "https://github.com/rust-minidump/minidump-writer"
homepage = "https://github.com/rust-minidump/minidump-writer"
edition = "2021"
license = "MIT"

[dependencies]
byteorder = "1.3.2"
cfg-if = "1.0"
crash-context = "0.4"
memoffset = "0.6"
minidump-common = "0.12"
scroll = "0.11"
tempfile = "3.1.0"
thiserror = "1.0.21"

[target.'cfg(unix)'.dependencies]
libc = "0.2.74"
goblin = "0.5"
memmap2 = "0.5"

[target.'cfg(any(target_os = "linux", target_os = "android"))'.dependencies]
nix = { version = "0.24", default-features = false, features = [
    "mman",
    "process",
    "ptrace",
    "user",
] }

[target.'cfg(target_os = "windows")'.dependencies.windows-sys]
version = "0.36"
features = [
    # MiniDumpWriteDump requires...a lot of features
    "Win32_Foundation",
    "Win32_Storage_FileSystem",
    "Win32_System_Diagnostics_Debug",
    "Win32_System_Kernel",
    "Win32_System_Memory",
    # VerifierEnumerateResource and friends
    "Win32_System_ApplicationVerifier",
    # GetCurrentThreadId & OpenProcess
    "Win32_System_Threading",
]

[target.'cfg(target_os = "macos")'.dependencies]
# Binds some additional mac specifics not in libc
mach2 = "0.4"

[dev-dependencies]
# Minidump-processor is async so we need an executor
futures = { version = "0.3", features = ["executor"] }
minidump = "0.12"
memmap2 = "0.5"

[target.'cfg(target_os = "macos")'.dev-dependencies]
# We dump symbols for the `test` executable so that we can validate that minidumps
# created by this crate can be processed by minidump-processor
dump_syms = { version = "1.0.1", default-features = false }
minidump-processor = { version = "0.12", default-features = false }
similar-asserts = "1.2"
uuid = "1.0"
