[package]
name = "minidump_writer_linux"
version = "0.1.0"
authors = ["Martin Sirringhaus"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cfg-if = "*"
tempfile = "*"
nix = "*"